"use client";
import { useI18n } from "@/lib/i18n";
import { useState } from "react";
import { BookOpen, Search, FileText, ShieldCheck, ArrowRight, X } from "lucide-react";
import { useResource } from "@/lib/use-resource";
import { post, errorMessage } from "@/lib/api";
import type { Citation, KnowledgeDocument, KnowledgeSearch } from "@/lib/types";
import { PageHeading, LoadingState, ErrorState, DemoNote, EmptyState, Button, Panel } from "@/components/ui";
import { CitationCard } from "@/components/risk";
import { JurisdictionContext } from "@/components/jurisdiction-context";
import { useProject } from "@/lib/project-context";
export default function KnowledgePage() {
  const { t } = useI18n();
  const { projectId } = useProject();
  const docs = useResource<KnowledgeDocument[]>("/knowledge/documents" + (projectId ? "?project_id="+projectId : ""));
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<KnowledgeDocument | null>(null);
  const [query, setQuery] = useState(""); const [hazard, setHazard] = useState("working_at_height");
  const [resultProject, setResultProject] = useState(0);
  const [result, setResult] = useState<KnowledgeSearch | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const filtered = docs.data?.filter((d) => (d.document_title + d.document_type + d.jurisdiction).toLowerCase().includes(search.toLowerCase())) ?? [];
  async function retrieve() {
    setResultProject(projectId); setBusy(true); setError(""); setResult(null);
    try { setResult(await post<KnowledgeSearch>("/knowledge/search", { query, hazard_type: hazard, project_id: projectId || null })); }
    catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  return <><PageHeading eyebrow={t("REASON / KNOWLEDGE LIBRARY")} title={t("Good decisions need grounded evidence.")} description={t("Verified safety guidance for the active project jurisdiction.")}><span className="mode-badge"><BookOpen size={15} />{t("Jurisdiction-aware safety guidance")}</span></PageHeading>
    <JurisdictionContext /><div className="info-callout"><strong>{t("Verified origin. Professional judgment.")}</strong><p>{t("SafeSite provides AI-assisted retrieval of official safety guidance. It is not legal advice and does not replace qualified safety professionals. Codes, guides and handbooks retain their source type. Demo records remain unverified.")}</p></div>
    <Panel title={t("Search verified sources")} subtitle={t("Find passages relevant to an observed hazard. Results are limited to three.")}><form className="panel-body review-fields" onSubmit={(e) => { e.preventDefault(); void retrieve(); }}><div className="field-row"><label>{t("Observed hazard")}<select value={hazard} onChange={(e) => setHazard(e.target.value)}>{["working_at_height","unprotected_edge","missing_ppe","unsafe_scaffolding","electrical_hazard","housekeeping"].map((h) => <option key={h} value={h}>{t(h)}</option>)}</select></label><label>{t("Search official safety passages")}<input required minLength={3} maxLength={1000} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t("fall protection exposed slab edge")} /></label></div><Button type="submit" busy={busy} disabled={query.trim().length < 3}><Search size={16} />{t("Search verified guidance")}</Button>{error && <ErrorState message={error} />}{result && resultProject === projectId && <div aria-label={t("Verified search results")}><p className="info-callout">{t(result.message)}</p><p className="micro">{result.candidate_count} {" "}{t("candidates /")}{" "}{result.latency_ms} {" "}{t("ms / relevance scores are retrieval scores, not legal certainty.")}</p>{result.citations.map((c) => <CitationCard key={c.chunk_id} citation={{ ...c, id: c.chunk_id!, source_reference: c.source_url!, is_demo: false } as Citation} />)}</div>}</form></Panel>
    <div className="knowledge-toolbar"><h2>{t("Safety documents")}{" "}<span className="count-chip">{docs.data?.length ?? 0}</span></h2><div className="input-with-icon"><Search size={16} /><input aria-label={t("Search documents")} placeholder={t("Search the library")} value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    {docs.loading ? <LoadingState /> : docs.error ? <ErrorState message={docs.error} retry={docs.reload} /> : <div className="document-grid">{filtered.map((doc) => <article className="document-card" data-demo={doc.is_demo} key={doc.id}><div className="document-card-top"><span className="document-icon"><FileText size={27} /></span><span className="sample-label">{doc.is_demo ? t("Demo / Unverified") : doc.verified ? t("VERIFIED SOURCE") : t("Unverified")}</span></div><h3>{doc.document_title}</h3><p>{doc.is_demo ? doc.excerpt : t(doc.excerpt)}</p><dl><div><dt>{t("Authority")}</dt><dd>{t(doc.authority ?? "Demo author")}</dd></div><div><dt>{t("Jurisdiction")}</dt><dd>{t(doc.jurisdiction)}</dd></div><div><dt>{t("Document type")}</dt><dd>{t(doc.document_type)}</dd></div><div><dt>{t("Verification")}</dt><dd>{doc.verified ? t("Official source origin verified") : t("Not verified")}</dd></div>{!doc.is_demo && <><div><dt>{t("Status")}</dt><dd>{doc.active ? t("Active indexed version") : t("Inactive / historical")}</dd></div><div><dt>{t("Version")}</dt><dd>{doc.version ?? t("Publication date not established")}{doc.effective_date ? t(" / Effective ")+doc.effective_date : ""}</dd></div><div><dt>{t("Passages")}</dt><dd>{doc.indexed_chunk_count} {" "}{t("indexed /")}{" "}{doc.chunk_count} {" "}{t("stored")}</dd></div>{doc.related_source_key && <div><dt>{t("Amends")}</dt><dd>{doc.related_source_key}</dd></div>}</>}</dl>{doc.is_demo ? <button className="text-link" onClick={() => setSelected(doc)}>{t("View sample document")}{" "}<ArrowRight size={15} /></button> : <><a className="text-link" href={doc.source_url} target="_blank" rel="noreferrer">{t("Open official source")}{" "}<ArrowRight size={15} /></a>{!!doc.quality_notes?.length && <details><summary className="micro">{t("Indexing limitations (")}{doc.quality_notes.length})</summary><ul className="micro">{doc.quality_notes.map((n,i) => <li key={i}>{t(n)}</li>)}</ul></details>}</>}</article>)}</div>}
    {!docs.loading && !docs.error && !filtered.length && <EmptyState title={t("No matching documents")}><p>{t("Try a broader search term.")}</p></EmptyState>}
    {selected && <section className="document-preview" aria-label={t("Sample document preview")}><div className="panel-heading"><div><div className="eyebrow">{t("SAMPLE DOCUMENT PREVIEW")}</div><h2>{selected.document_title}</h2></div><Button variant="secondary" onClick={() => setSelected(null)} aria-label={t("Close document preview")}><X size={16} /></Button></div><div className="panel-body"><span className="sample-label">{t("Demo regulation data")}</span><h3>{selected.section}</h3><p>{selected.excerpt}</p><code>{selected.source_reference}</code><DemoNote>{t("This is an authored sample for demonstrating the citation UI. It is not a retrieved legal document.")}</DemoNote></div></section>}
    <div className="knowledge-roadmap"><ShieldCheck size={29} /><div><h3>{t("Evidence has a source.")}</h3><p>{t("Only registered official documents enter verified retrieval. Known amended passages and inactive versions are excluded. Missing or weak matches remain explicit evidence gaps.")}</p></div></div></>;
}
