"use client";
import { useI18n } from "@/lib/i18n";
import { useState } from "react";
import { ScanLine, ShieldCheck, ArrowRight } from "lucide-react";
import type { Incident, AIHealth } from "@/lib/types";
import { Button, Panel } from "./ui";
import { AnalysisSource } from "./analysis-source";
import { RiskBreakdown } from "./risk";
import { useResource } from "@/lib/use-resource";
import { ImageUpload } from "./image-upload";
import { imageUrl, humanize } from "@/lib/api";
export function ReinspectionPanel({ incident, busy, onReinspect, onClose, onReturn }: { incident: Incident; busy: boolean; onReinspect: (file: File | null, useDemo: boolean, notes: string) => void; onClose: () => void; onReturn: () => void }) {
  const { t } = useI18n();
  const health = useResource<AIHealth>("/health"); const configured = health.data?.reinspection; const real = configured ? configured.provider !== "mock" : health.data?.ai_mode === "real"; const ready = configured?.ready ?? health.data?.ai_ready;
  const [file, setFile] = useState<File | null>(null); const [demo, setDemo] = useState(false); const [notes, setNotes] = useState("");
  const result = incident.reinspection_json; const complete = incident.corrective_actions.length > 0 && incident.corrective_actions.every((a) => a.status === "COMPLETED");
  return <Panel title={t("Reinspection")} subtitle={t("Verify corrective work. Keep the final decision human.")}><div className="panel-body">
    {incident.status === "RECTIFICATION" && <div className="reinspect-form"><ImageUpload file={file} onChange={setFile} disabled={busy} required={real} label={t("Rectification evidence")} />{!real && <label className="check-label"><input type="checkbox" checked={demo} onChange={(e) => setDemo(e.target.checked)} />{t("Use simulated rectification evidence for this demo")}</label>}<label>{t("Rectification notes")}<textarea rows={2} maxLength={4000} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={t("Describe the work completed and the evidence provided.")} /></label>{!complete && <p className="micro">{t("Complete every corrective action above to enable reinspection.")}</p>}<Button busy={busy} disabled={!ready || !complete || (!file && (real || !demo))} onClick={() => onReinspect(file, real ? false : demo, notes)}><ScanLine size={16} />{t("Run Reinspection")}</Button><div className="info-callout">{t(health.error || (configured ? configured.error : health.data?.ai_error) || (real ? t("REAL AI compares the original hazard and images with your new evidence. It can recommend closure; only you can close the case.") : t("DEMO AI: reinspection is simulated; the mock provider does not evaluate image content.")))}</div></div>}
    {result ? <><AnalysisSource source={incident.reinspection_source} /><div className="reinspection-outcome"><ShieldCheck size={24} /><div><h3>{result.hazard_still_present ? t("Hazard still present") : result.recommendation === "ELIGIBLE_FOR_CLOSURE" ? t("Hazard Mitigated") : t("Mitigation requires human review")}</h3><p>{t("AI assessment ·")}{" "}{Math.round(result.mitigation_confidence * 100)}{t("% mitigation confidence")}</p></div></div><div className="risk-comparison"><div><span>{t("Previous Risk")}</span><strong>{result.previous_risk_score}<small>/100</small></strong></div><ArrowRight size={25} /><div><span>{t("Current Risk")}</span><strong className="teal-text">{result.current_risk_score}<small>/100</small></strong></div></div>{result.current_risk_breakdown && <RiskBreakdown risk={result.current_risk_breakdown} />}<ul className="evidence-list">{result.evidence.map((e) => <li key={t(e)}><span />{t(e)}</li>)}</ul><div className="recommendation"><span>{t("AI recommendation")}</span><strong>{humanize(result.recommendation)}</strong></div>{incident.rectification_evidence?.startsWith("/uploads/") && <a className="text-link" href={imageUrl(incident.rectification_evidence)} target="_blank" rel="noreferrer">{t("View saved rectification image")}{" "}<ArrowRight size={14} /></a>}{incident.rectification_notes && <p className="micro">{incident.rectification_notes}</p>}
    {incident.status === "REINSPECTION" && <div className="closure-controls"><p>{t("Review the evidence before closing. This recommendation never closes the case automatically.")}</p><div className="button-row"><Button variant="secondary" disabled={busy} onClick={onReturn}>{t("Return to rectification")}</Button>{result.recommendation === "ELIGIBLE_FOR_CLOSURE" && <Button busy={busy} onClick={onClose}><ShieldCheck size={16} />{t("Close Case")}</Button>}</div></div>}</> : incident.status !== "RECTIFICATION" && <div className="quiet-state"><ScanLine size={30} /><h3>{t("Evidence comes next.")}</h3><p>{t("Start rectification and complete the corrective actions to unlock reinspection.")}</p></div>}
  </div></Panel>;
}
