"use client";
import { useI18n } from "@/lib/i18n";
import { ShieldAlert, BookOpen, Check, Eye } from "lucide-react";
import type { Hazard, Citation, AnalysisProvenance, RiskBreakdown as RiskData } from "@/lib/types";
import { Badge, Panel } from "./ui";
export function RiskBreakdown({ risk }: { risk: RiskData }) {
  const { t } = useI18n();
  return <div className="risk-breakdown"><div className="factor-grid">{[[t("Severity"), risk.severity, 5], [t("Exposure"), risk.exposure, 5], [t("Probability"), risk.probability, 4]].map(([label, value, max]) => <div className="factor" key={t(label)}><span>{t(label)}</span><strong>{value}<small> / {max}</small></strong><div className="factor-track"><span style={{ width: Number(value) / Number(max) * 100 + "%" }} /></div></div>)}<div className="factor final-factor"><span>{t("Final risk")}</span><strong>{risk.final_score}<small> / 100</small></strong><Badge value={risk.risk_level} /></div></div><p className="micro">{t(risk.formula)}</p>{risk.overrides.map((o) => <div className="policy-note" key={t(o)}><ShieldAlert size={16} /><span>{t(o)}</span></div>)}<div className="micro">{t("Raw score")}{" "}{risk.raw_score} {" "}{t("· Policy")}{" "}{risk.policy_version}</div></div>;
}
export function CitationCard({ citation }: { citation: Citation }) {
  const { t } = useI18n();
  const url = citation.source_url;
  const official = url?.startsWith("https://www.labour.gov.hk/");
  return <div className="citation-card"><div className="citation-top"><BookOpen size={17} /><strong>{citation.document_title}</strong></div><span className="sample-label">{citation.is_demo ? t("Demo regulation data") : citation.verified ? t("VERIFIED SOURCE") : t("Unverified source")}</span>{citation.document_type && <p className="micro">{t(citation.document_type)} / {t(citation.authority)}</p>}<p className="micro source-text-label">{t(citation.verified && !citation.is_demo ? "Official Source Text" : "Source text")}</p><p translate="no" data-official-source-text>{citation.excerpt.length > 440 ? citation.excerpt.slice(0,440)+"..." : citation.excerpt}</p>{citation.excerpt.length > 440 && <details><summary>{t("Read stored passage")}</summary><p translate="no" data-official-source-text>{citation.excerpt}</p></details>}<small>{citation.section}{citation.page_number ? t(" / PDF page ")+citation.page_number : ""} / {t(citation.jurisdiction)}</small>{citation.version && <div className="micro">{citation.version}{citation.effective_date ? t(" / Effective ")+citation.effective_date : ""}</div>}{citation.related_source_key && <p className="micro">{t("Amends:")}{" "}{citation.related_source_key}</p>}{official ? <a className="text-link" href={url+"#page="+(citation.page_number ?? 1)} target="_blank" rel="noreferrer">{t("Open official source")}</a> : <div className="source-reference">{citation.source_reference}</div>}</div>;
}
export function HazardCard({ hazard, index, source }: { hazard: Hazard; index: number; source?: AnalysisProvenance }) {
  const { t } = useI18n();
  return <Panel className="hazard-card"><div className="hazard-heading"><span className="hazard-number">0{index + 1}</span><div><h2>{t(hazard.title)}</h2><p>{t(hazard.description)}</p></div><Badge value={hazard.risk_level} /></div><div className="confidence-line"><Eye size={15} />{Math.round(hazard.confidence * 100)}{t("% model confidence")}{" "}<span>· {source?.kind === "DEMO_AI" ? t("Simulated observation") : t("Review visual evidence")}</span>{hazard.confidence < .85 && <strong>{hazard.confidence < .60 ? t("Insufficient / uncertain evidence") : t("Human review required")}</strong>}</div><div className="hazard-columns"><div><h3 className="section-label">{t("Visual evidence")}</h3><ul className="evidence-list">{hazard.evidence.map((e) => <li key={t(e)}><span />{t(e)}</li>)}</ul><h3 className="section-label">{t("Risk assessment")}</h3><RiskBreakdown risk={hazard.risk_breakdown} /></div><div><h3 className="section-label">{t("Applicable Safety Guidance")}</h3>{hazard.citations.length ? hazard.citations.map((c) => <CitationCard key={c.id} citation={c} />) : <p className="guidance-empty">{t(hazard.guidance_message ?? "No sufficiently relevant verified safety source was retrieved.")}</p>}<h3 className="section-label">{t("Recommended corrective actions")}</h3><ul className="action-recommendations">{hazard.recommended_actions.map((a) => <li key={t(a)}><Check size={15} />{t(a)}</li>)}</ul></div></div></Panel>;
}
