export type RiskLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type IncidentStatus = "OPEN" | "UNDER_REVIEW" | "RECTIFICATION" | "REINSPECTION" | "CLOSED" | "REJECTED";
export interface Site { id: number; project_id: number; name: string; zone: string }
export interface Project { regulatory_jurisdiction?: string; id: number; name: string; code: string; location: string; sites: Site[] }
export interface Citation { chunk_id?: number; document_id?: number; authority?: string; source_url?: string; page_number?: number; section_heading?: string; version?: string | null; effective_date?: string | null; active?: boolean; retrieval_score?: number; related_source_key?: string | null; id: number | string; document_title: string; section: string; jurisdiction: string; excerpt: string; source_reference: string; verified: boolean; is_demo: boolean; document_type?: string; status?: string }
export interface RiskBreakdown { severity: number; exposure: number; probability: number; raw_score: number; final_score: number; risk_level: RiskLevel; confidence: number; requires_human_review: boolean; policy_version: string; overrides: string[]; formula: string }
export interface Hazard { guidance_message?: string | null; id: number; hazard_type: string; title: string; description: string; evidence: string[]; confidence: number; risk_score: number; risk_level: RiskLevel; risk_breakdown: RiskBreakdown; recommended_actions: string[]; citations: Citation[]; ai_generated: boolean }
export interface AnalysisProvenance { kind: "REAL_AI" | "DEMO_AI" | "UNKNOWN"; provider?: string | null; model_name?: string | null; prompt_version?: string | null }
export interface WorkloadHealth { provider: string; model: string; ready: boolean; error: string | null }
export interface AIHealth { vision?: WorkloadHealth; reinspection?: WorkloadHealth; ai_mode: "real" | "mock"; ai_ready: boolean; ai_error: string | null; vision_model: string | null }
export interface Inspection { analysis_source: AnalysisProvenance; id: number; project_id: number; site_id: number; location_text: string; source_type: string; image_path: string | null; description: string | null; status: string; created_at: string; completed_at: string | null; hazards: Hazard[]; incident_ids: number[]; review_notes: string | null; analysis_json: { summary: string; overall_confidence: number; requires_human_review: boolean; reasoning_notes: string[] } | null }
export interface CorrectiveAction { id: number; action_text: string; priority: string; assigned_to: string; status: string; completed_at: string | null }
export interface Reinspection { current_risk_breakdown?: RiskBreakdown | null; original_incident_id: number; hazard_still_present: boolean; mitigation_confidence: number; evidence: string[]; previous_risk_score: number; current_risk_score: number; recommendation: "KEEP_OPEN" | "HUMAN_REVIEW" | "ELIGIBLE_FOR_CLOSURE" }
export interface Incident { analysis_source: AnalysisProvenance; reinspection_source: AnalysisProvenance; id: number; incident_code: string; title: string; description: string; project_name: string; site_name: string; location_text: string; assigned_to: string; deadline: string | null; risk_score: number; risk_level: RiskLevel; status: IncidentStatus; human_decision: string; created_at: string; closed_at: string | null; hazard: Hazard; corrective_actions: CorrectiveAction[]; reinspection_json: Reinspection | null; rectification_evidence: string | null; rectification_notes: string | null; image_path: string | null; inspection_id: number }
export interface Audit { id: number; action: string; actor_type: string; actor_name: string; created_at: string; previous_value: Record<string, unknown> | null; new_value: Record<string, unknown> | null; metadata_json: Record<string, unknown> | null }
export interface Dashboard { safety_risk_score: number; open_incidents: number; critical_incidents: number; resolved_incidents: number; total_incidents: number; closure_rate: number; recent_incidents: Incident[]; score_definition: string }
export interface Trend { date: string; risk_score: number; open_incidents: number }
export interface HazardCount { hazard_type: string; name: string; count: number }
export interface Execution { id: number; workflow_name: string; model_provider: string; model_name: string; prompt_version: string; policy_version: string; status: string; latency_ms: number | null; confidence: number | null; created_at: string }

export interface KnowledgeDocument extends Citation { authority?: string; active?: boolean; chunk_count?: number; indexed_chunk_count?: number; quality_notes?: string[] }
export interface KnowledgeSearch { status: string; message: string; citations: Citation[]; candidate_count: number; latency_ms: number }
